name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www

            # First time setup
            if [ ! -d "app" ]; then
              git clone https://github.com/theBrainly/sample.git app
            fi

            cd app

          
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            # Install dependencies
            npm install

            # Restart app
            pm2 delete app || true
            pm2 start server.js --name app